package HelloWorldApp;


/**
* HelloWorldApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Sunday, October 26, 2025 9:10:04 PM WEST
*/

public interface HelloOperations 
{
  String HelloMessage ();
  void HelloMessage (String newHelloMessage);
} // interface HelloOperations
